-- MySQL Script generated by MySQL Workbench
-- Thursday 11 January 2018 11:56:49 AM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema contest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema contest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `contest` DEFAULT CHARACTER SET utf8 ;
USE `contest` ;

-- -----------------------------------------------------
-- Table `contest`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` TEXT(50) NOT NULL,
  `role_desc` TEXT(100) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contest`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest`.`permissions` (
  `permission_id` INT NOT NULL AUTO_INCREMENT,
  `permission_name` TEXT(50) NOT NULL,
  `permission_desc` TEXT(100) NOT NULL,
  PRIMARY KEY (`permission_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contest`.`roles_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest`.`roles_permissions` (
  `role_permission_id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`role_permission_id`),
  INDEX `fk_role_id_rolesperm` (`role_id` ASC),
  INDEX `fk_permission_id_rolesperm` (`permission_id` ASC),
  CONSTRAINT `fk_role_id_rolesperm`
    FOREIGN KEY (`role_id`)
    REFERENCES `contest`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permission_id_rolesperm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `contest`.`permissions` (`permission_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contest`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` TEXT(50) NOT NULL,
  `user_email` VARCHAR(100) NOT NULL,
  `user_password` VARCHAR(150) NOT NULL,
  `user_active` TINYINT(1) NOT NULL,
  `created_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_mod_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contest`.`users_role_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest`.`users_role_permissions` (
  `user_role_permission_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_role_permission_id`),
  INDEX `fk_user_id_userrolesperm` (`user_id` ASC),
  INDEX `fk_role_id_userrolesperm` (`role_id` ASC),
  CONSTRAINT `fk_user_id_userrolesperm`
    FOREIGN KEY (`user_id`)
    REFERENCES `contest`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_id_userrolesperm`
    FOREIGN KEY (`role_id`)
    REFERENCES `contest`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contest`.`event_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest`.`event_types` (
  `event_type_id` INT NOT NULL AUTO_INCREMENT,
  `event_type_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`event_type_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `contest`.`plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest`.`plans` (
  `plan_id` INT NOT NULL AUTO_INCREMENT,
  `plan_name` VARCHAR(50) NOT NULL,
  `plan_price` INT NOT NULL,
  `participant_count` INT NOT NULL,
  `plan_json` JSON NOT NULL,
  `plan_promoted` TINYINT(1) NOT NULL,
  PRIMARY KEY (`plan_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `contest`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest`.`events` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `conducted_by` INT NOT NULL,
  `event_type_id` INT NOT NULL,
  `event_desc` VARCHAR(200) NULL,
  `event_rules` VARCHAR(300) NOT NULL,
  `event_name` VARCHAR(50) NOT NULL,
  `event_participants` INT NOT NULL,
  `created_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_mod_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `plan_id` INT NOT NULL,
  `event_cover` MEDIUMTEXT NULL,
  PRIMARY KEY (`event_id`),
  INDEX `fk_conducted_by_events` (`conducted_by` ASC),
  INDEX `fk_event_type_id_events` (`event_type_id` ASC),
  INDEX `fk_events_plan_id_events` (`plan_id` ASC),
  CONSTRAINT `fk_conducted_by_events`
    FOREIGN KEY (`conducted_by`)
    REFERENCES `contest`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_type_id_events`
    FOREIGN KEY (`event_type_id`)
    REFERENCES `contest`.`event_types` (`event_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_plan_id_events`
    FOREIGN KEY (`plan_id`)
    REFERENCES `contest`.`plans` (`plan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `contest`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest`.`images` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `image_content` LONGBLOB NOT NULL,
  `image_desc` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contest`.`themes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest`.`themes` (
  `theme_id` INT NOT NULL AUTO_INCREMENT,
  `theme_name` VARCHAR(50) NOT NULL,
  `image_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`theme_id`),
  INDEX `fk_image_id_themes` (`image_id` ASC),
  INDEX `fk_event_id_themes` (`event_id` ASC),
  CONSTRAINT `fk_image_id_themes`
    FOREIGN KEY (`image_id`)
    REFERENCES `contest`.`images` (`image_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_id_themes`
    FOREIGN KEY (`event_id`)
    REFERENCES `contest`.`events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contest`.`gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest`.`gallery` (
  `gallery_id` INT NOT NULL AUTO_INCREMENT,
  `image_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`gallery_id`),
  INDEX `fk_image_id_gallery` (`image_id` ASC),
  INDEX `fk_event_id_gallery` (`event_id` ASC),
  CONSTRAINT `fk_image_id_gallery`
    FOREIGN KEY (`image_id`)
    REFERENCES `contest`.`images` (`image_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_id_gallery`
    FOREIGN KEY (`event_id`)
    REFERENCES `contest`.`events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contest`.`users_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest`.`users_images` (
  `user_id` INT NOT NULL,
  `image_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `theme_id` INT NOT NULL,
  PRIMARY KEY (`image_id`, `user_id`, `event_id`, `theme_id`),
  INDEX `fk_user_id_userimages` (`user_id` ASC),
  INDEX `fk_event_id_userimages` (`event_id` ASC),
  INDEX `fk_theme_id_userimages` (`theme_id` ASC),
  INDEX `fk_image_id_userimages` (`image_id` ASC),
  CONSTRAINT `fk_user_id_userimages`
    FOREIGN KEY (`user_id`)
    REFERENCES `contest`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_image_id_userimages`
    FOREIGN KEY (`image_id`)
    REFERENCES `contest`.`images` (`image_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_id_userimages`
    FOREIGN KEY (`event_id`)
    REFERENCES `contest`.`events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_theme_id_userimages`
    FOREIGN KEY (`theme_id`)
    REFERENCES `contest`.`themes` (`theme_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contest`.`user_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest`.`user_likes` (
  `user_id` INT NOT NULL,
  `image_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `image_id`),
  INDEX `fk_image_id_userlikes` (`image_id` ASC),
  INDEX `fk_user_id_userlikes` (`user_id` ASC),
  CONSTRAINT `fk_user_id_userlikes`
    FOREIGN KEY (`user_id`)
    REFERENCES `contest`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_image_id_userlikes`
    FOREIGN KEY (`image_id`)
    REFERENCES `contest`.`images` (`image_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contest`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest`.`questions` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NOT NULL,
  `question_string` VARCHAR(100) NOT NULL,
  `question_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`question_id`),
  INDEX `fk_event_id_questions` (`event_id` ASC),
  CONSTRAINT `fk_event_id_questions`
    FOREIGN KEY (`event_id`)
    REFERENCES `contest`.`events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contest`.`question_responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest`.`question_responses` (
  `question_response_id` INT NOT NULL AUTO_INCREMENT,
  `question_id` INT NOT NULL,
  `response_available` JSON NOT NULL,
  PRIMARY KEY (`question_response_id`),
  INDEX `fk_question_id_questionresponses` (`question_id` ASC),
  CONSTRAINT `fk_question_id_questionresponses`
    FOREIGN KEY (`question_id`)
    REFERENCES `contest`.`questions` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contest`.`user_question_responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest`.`user_question_responses` (
  `user_question_response_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `user_response` JSON NULL,
  PRIMARY KEY (`user_question_response_id`),
  INDEX `fk_user_id_userquesresponses` (`user_id` ASC),
  INDEX `fk_question_id_userquesresponses` (`question_id` ASC),
  CONSTRAINT `fk_user_id_userquesresponses`
    FOREIGN KEY (`user_id`)
    REFERENCES `contest`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_id_userquesresponses`
    FOREIGN KEY (`question_id`)
    REFERENCES `contest`.`questions` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contest`.`evaluate_responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contest`.`evaluate_responses` (
  `evaluate_response_id` INT NOT NULL AUTO_INCREMENT,
  `user_question_response_id` INT NOT NULL,
  `score` INT NOT NULL,
  PRIMARY KEY (`evaluate_response_id`),
  INDEX `fk_user_ques_resp_id_evalresponses` (`user_question_response_id` ASC),
  CONSTRAINT `fk_user_ques_resp_id_evalresponses`
    FOREIGN KEY (`user_question_response_id`)
    REFERENCES `contest`.`user_question_responses` (`user_question_response_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
